### ISSUE TITLE
Site name, slogan, and Heading options don't seem to work. 

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/maintenance_page#2]
These options don't seem to work.

![Maintenance_mode___Virtual_User_Group](https://user-images.githubusercontent.com/3144571/61194554-c9538300-a687-11e9-828f-f92c288d814a.png)

**Comment by ghost** [comment]
They don't work in populating the page title in the browser tab, or are you expecting them to change what appears on the page itself?

**Comment by stpaultim** [comment]
I was expecting them to effect the page itself, which is why I also opened the issue about the logo.

I do see "Display these components in the page title (e.g. browser tab)." I think this message confused me, because I couldn't imagine the usefulness of having all three in the browser tab. If the first one is selected, I'll never see the effect of the other two.

If I had the choice of selecting one, it might have made more sense to me. 

Anyway, thanks for the reply. It appears I simply misunderstood.

Works as intended.

**Comment by ghost** [comment]
No, three together isn't really useful, but that's why they're checkboxes so you can choose what to show (and what not to show). I, for example, usually have the first two ticked (e.g. 'Site under maintenance - Packweb')
